<script type="text/javascript" src="${ pageContext.request.contextPath}/js/jquery-1.8.0.js?v=1"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/jquery-easyui-1.4.1/jquery.easyui.min.js?v=1"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/ztree/js/jquery.ztree.core-3.5.js?v=1"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/jquery-easyui-1.4.1/locale/easyui-lang-zh_CN.js?v=1"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/check.js?v=1"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/kingeditor/kindeditor.js"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/kingeditor/lang/zh_CN.js"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/kingeditor/plugins/code/prettify.js"></script>
<script type="text/javascript" src="${ pageContext.request.contextPath}/js/layer/layer.min.js"></script>
